package com.skysoft.repository;

import com.skysoft.domain.Druggds;

public interface DruggdsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_gds
     *
     * @mbggenerated Sun Jan 18 01:22:18 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_gds
     *
     * @mbggenerated Sun Jan 18 01:22:18 CST 2015
     */
    int insert(Druggds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_gds
     *
     * @mbggenerated Sun Jan 18 01:22:18 CST 2015
     */
    int insertSelective(Druggds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_gds
     *
     * @mbggenerated Sun Jan 18 01:22:18 CST 2015
     */
    Druggds selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_gds
     *
     * @mbggenerated Sun Jan 18 01:22:18 CST 2015
     */
    int updateByPrimaryKeySelective(Druggds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_gds
     *
     * @mbggenerated Sun Jan 18 01:22:18 CST 2015
     */
    int updateByPrimaryKey(Druggds record);
}