package com.skysoft.domain;

import java.io.Serializable;

public class druggds implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_gds.ID
     *
     * @mbggenerated Thu Jan 23 14:30:40 CST 2014
     */
    private Integer ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_gds.DrugBrand
     *
     * @mbggenerated Thu Jan 23 14:30:40 CST 2014
     */
    private String drugBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_gds.ProductionUnit
     *
     * @mbggenerated Thu Jan 23 14:30:40 CST 2014
     */
    private String productionUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_gds.DrugGDS
     *
     * @mbggenerated Thu Jan 23 14:30:40 CST 2014
     */
    private String drugGDS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_gds.DrugName
     *
     * @mbggenerated Thu Jan 23 14:30:40 CST 2014
     */
    private String drugName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_gds.Specification
     *
     * @mbggenerated Thu Jan 23 14:30:40 CST 2014
     */
    private String specification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_gds.Sescription
     *
     * @mbggenerated Thu Jan 23 14:30:40 CST 2014
     */
    private String sescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_gds.ID
     *
     * @return the value of drug_gds.ID
     *
     * @mbggenerated Thu Jan 23 14:30:40 CST 2014
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_gds.ID
     *
     * @param ID the value for drug_gds.ID
     *
     * @mbggenerated Thu Jan 23 14:30:40 CST 2014
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_gds.DrugBrand
     *
     * @return the value of drug_gds.DrugBrand
     *
     * @mbggenerated Thu Jan 23 14:30:40 CST 2014
     */
    public String getDrugBrand() {
        return drugBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_gds.DrugBrand
     *
     * @param drugBrand the value for drug_gds.DrugBrand
     *
     * @mbggenerated Thu Jan 23 14:30:40 CST 2014
     */
    public void setDrugBrand(String drugBrand) {
        this.drugBrand = drugBrand == null ? null : drugBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_gds.ProductionUnit
     *
     * @return the value of drug_gds.ProductionUnit
     *
     * @mbggenerated Thu Jan 23 14:30:40 CST 2014
     */
    public String getProductionUnit() {
        return productionUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_gds.ProductionUnit
     *
     * @param productionUnit the value for drug_gds.ProductionUnit
     *
     * @mbggenerated Thu Jan 23 14:30:40 CST 2014
     */
    public void setProductionUnit(String productionUnit) {
        this.productionUnit = productionUnit == null ? null : productionUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_gds.DrugGDS
     *
     * @return the value of drug_gds.DrugGDS
     *
     * @mbggenerated Thu Jan 23 14:30:40 CST 2014
     */
    public String getDrugGDS() {
        return drugGDS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_gds.DrugGDS
     *
     * @param drugGDS the value for drug_gds.DrugGDS
     *
     * @mbggenerated Thu Jan 23 14:30:40 CST 2014
     */
    public void setDrugGDS(String drugGDS) {
        this.drugGDS = drugGDS == null ? null : drugGDS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_gds.DrugName
     *
     * @return the value of drug_gds.DrugName
     *
     * @mbggenerated Thu Jan 23 14:30:40 CST 2014
     */
    public String getDrugName() {
        return drugName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_gds.DrugName
     *
     * @param drugName the value for drug_gds.DrugName
     *
     * @mbggenerated Thu Jan 23 14:30:40 CST 2014
     */
    public void setDrugName(String drugName) {
        this.drugName = drugName == null ? null : drugName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_gds.Specification
     *
     * @return the value of drug_gds.Specification
     *
     * @mbggenerated Thu Jan 23 14:30:40 CST 2014
     */
    public String getSpecification() {
        return specification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_gds.Specification
     *
     * @param specification the value for drug_gds.Specification
     *
     * @mbggenerated Thu Jan 23 14:30:40 CST 2014
     */
    public void setSpecification(String specification) {
        this.specification = specification == null ? null : specification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_gds.Sescription
     *
     * @return the value of drug_gds.Sescription
     *
     * @mbggenerated Thu Jan 23 14:30:40 CST 2014
     */
    public String getSescription() {
        return sescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_gds.Sescription
     *
     * @param sescription the value for drug_gds.Sescription
     *
     * @mbggenerated Thu Jan 23 14:30:40 CST 2014
     */
    public void setSescription(String sescription) {
        this.sescription = sescription == null ? null : sescription.trim();
    }
}