package com.skysoft.domain;

public class Druggds {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_gds.id
     *
     * @mbggenerated Sun Jan 18 01:22:18 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_gds.drugBrand
     *
     * @mbggenerated Sun Jan 18 01:22:18 CST 2015
     */
    private String drugBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_gds.productionUnit
     *
     * @mbggenerated Sun Jan 18 01:22:18 CST 2015
     */
    private String productionUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_gds.drugGDS
     *
     * @mbggenerated Sun Jan 18 01:22:18 CST 2015
     */
    private String drugGDS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_gds.drugName
     *
     * @mbggenerated Sun Jan 18 01:22:18 CST 2015
     */
    private String drugName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_gds.specification
     *
     * @mbggenerated Sun Jan 18 01:22:18 CST 2015
     */
    private String specification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_gds.sescription
     *
     * @mbggenerated Sun Jan 18 01:22:18 CST 2015
     */
    private String sescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_gds.id
     *
     * @return the value of drug_gds.id
     * @mbggenerated Sun Jan 18 01:22:18 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_gds.id
     *
     * @param id the value for drug_gds.id
     * @mbggenerated Sun Jan 18 01:22:18 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_gds.drugBrand
     *
     * @return the value of drug_gds.drugBrand
     * @mbggenerated Sun Jan 18 01:22:18 CST 2015
     */
    public String getDrugBrand() {
        return drugBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_gds.drugBrand
     *
     * @param drugBrand the value for drug_gds.drugBrand
     * @mbggenerated Sun Jan 18 01:22:18 CST 2015
     */
    public void setDrugBrand(String drugBrand) {
        this.drugBrand = drugBrand == null ? null : drugBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_gds.productionUnit
     *
     * @return the value of drug_gds.productionUnit
     * @mbggenerated Sun Jan 18 01:22:18 CST 2015
     */
    public String getProductionUnit() {
        return productionUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_gds.productionUnit
     *
     * @param productionUnit the value for drug_gds.productionUnit
     * @mbggenerated Sun Jan 18 01:22:18 CST 2015
     */
    public void setProductionUnit(String productionUnit) {
        this.productionUnit = productionUnit == null ? null : productionUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_gds.drugGDS
     *
     * @return the value of drug_gds.drugGDS
     * @mbggenerated Sun Jan 18 01:22:18 CST 2015
     */
    public String getDrugGDS() {
        return drugGDS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_gds.drugGDS
     *
     * @param drugGDS the value for drug_gds.drugGDS
     * @mbggenerated Sun Jan 18 01:22:18 CST 2015
     */
    public void setDrugGDS(String drugGDS) {
        this.drugGDS = drugGDS == null ? null : drugGDS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_gds.drugName
     *
     * @return the value of drug_gds.drugName
     * @mbggenerated Sun Jan 18 01:22:18 CST 2015
     */
    public String getDrugName() {
        return drugName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_gds.drugName
     *
     * @param drugName the value for drug_gds.drugName
     * @mbggenerated Sun Jan 18 01:22:18 CST 2015
     */
    public void setDrugName(String drugName) {
        this.drugName = drugName == null ? null : drugName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_gds.specification
     *
     * @return the value of drug_gds.specification
     * @mbggenerated Sun Jan 18 01:22:18 CST 2015
     */
    public String getSpecification() {
        return specification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_gds.specification
     *
     * @param specification the value for drug_gds.specification
     * @mbggenerated Sun Jan 18 01:22:18 CST 2015
     */
    public void setSpecification(String specification) {
        this.specification = specification == null ? null : specification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_gds.sescription
     *
     * @return the value of drug_gds.sescription
     * @mbggenerated Sun Jan 18 01:22:18 CST 2015
     */
    public String getSescription() {
        return sescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_gds.sescription
     *
     * @param sescription the value for drug_gds.sescription
     * @mbggenerated Sun Jan 18 01:22:18 CST 2015
     */
    public void setSescription(String sescription) {
        this.sescription = sescription == null ? null : sescription.trim();
    }
}